import Weiwudi from "weiwudi";
import { MaplatMap } from "../map_ex";
import { Coordinate } from "ol/coordinate";
import { Feature, Polygon } from "@turf/turf";
import { Size } from "ol/size";
declare type Constructor<T = {}> = new (...args: any[]) => T;
declare type Condition = {
    x?: number;
    y?: number;
    latitude?: number;
    longitude?: number;
    mercZoom?: number;
    zoom?: number;
    direction?: number;
    rotation?: number;
};
export declare function setCustomFunction<TBase extends Constructor>(Base: TBase): {
    new (...args: any[]): {
        weiwudi?: Weiwudi | undefined;
        _map?: MaplatMap | undefined;
        homePosition?: Coordinate | undefined;
        mercZoom?: number | undefined;
        pois: any;
        officialTitle: string;
        title: string;
        mapID: string;
        label: string;
        initialWait?: Promise<any> | undefined;
        maxZoom?: number | undefined;
        minZoom?: number | undefined;
        envelope?: Feature<Polygon, import("@turf/helpers").Properties> | undefined;
        centroid?: number[] | undefined;
        insideCheckHistMapCoords(coord: Coordinate): boolean;
        getCacheEnable(): boolean;
        getTileCacheStatsAsync(): Promise<{
            size?: number | undefined;
            count?: number | undefined;
            total?: number | undefined;
            percent?: number | undefined;
        }>;
        getTileCacheSizeAsync(): Promise<number>;
        fetchAllTileCacheAsync(callback: any): Promise<void>;
        cancelTileCacheAsync(): Promise<void>;
        clearTileCacheAsync(): Promise<void>;
        getMap(): MaplatMap | undefined;
        setViewpointRadian(cond: Condition): void;
        setViewpoint(cond: Condition): void;
        goHome(): void;
        setGPSMarkerAsync(position: any, ignoreMove?: boolean): Promise<unknown>;
        setGPSMarker(position: any, ignoreMove?: boolean): void;
        mercsFromGivenMercZoom(center: Coordinate, mercZoom?: number | undefined, direction?: number | undefined): Coordinate[];
        mercsFromGPSValue(lnglat: Coordinate, acc: number): number[][];
        rotateMatrix(xys: number[][], theta?: number | undefined): Coordinate[];
        mercs2MercRotation(xys: Coordinate[]): number;
        resolvePois(pois?: any): Promise<void>;
        getPoi(id: string): undefined;
        addPoi(data: any, clusterId?: string | undefined): any;
        removePoi(id: string): void;
        clearPoi(clusterId?: string | undefined): void;
        listPoiLayers(hideOnly?: boolean, nonzero?: boolean): any[];
        getPoiLayer(id: string): any;
        addPoiLayer(id: string, data: any): void;
        removePoiLayer(id: string): void;
        merc2XyAsync(merc: Coordinate): Promise<Coordinate>;
        merc2XyAsync_ignoreBackground(merc: Coordinate): Promise<Coordinate | void>;
        xy2MercAsync(xy: Coordinate): Promise<Coordinate>;
        xy2SysCoord(xy: Coordinate): Coordinate;
        sysCoord2Xy(sysCoord: Coordinate): Coordinate;
        viewPoint2MercsAsync(center?: Coordinate | undefined, zoom?: number | undefined, rotate?: number | undefined, size?: Size | undefined): Promise<Coordinate[]>;
        mercs2ViewPointAsync(mercs: Coordinate[]): Promise<[Coordinate, number, number]>;
        mercs2SysCoordsAsync_multiLayer(mercs: Coordinate[]): Promise<(Coordinate[] | undefined)[]>;
        merc2SysCoordAsync_ignoreBackground(merc: Coordinate): Promise<Coordinate | void>;
        merc2SysCoordAsync(merc: Coordinate): Promise<Coordinate>;
        sysCoord2MercAsync(sysCoord: Coordinate): Promise<Coordinate>;
        zoom2Radius(size: Size, zoom?: number | undefined): number;
        viewPoint2SysCoords(center?: Coordinate | undefined, zoom?: number | undefined, rotate?: number | undefined, size?: Size | undefined): Coordinate[];
        mercViewPoint2Mercs(center?: Coordinate | undefined, zoom?: number | undefined, rotate?: number | undefined, size?: Size | undefined): Coordinate[];
        sysCoords2ViewPoint(sysCoords: Coordinate[]): [Coordinate, number, number];
        mercs2MercViewPoint(mercs: Coordinate[]): [Coordinate, number, number];
        sysCoords2Xys(sysCoords: Coordinate[]): Coordinate[];
        xys2SysCoords(xys: Coordinate[]): Coordinate[];
        mercs2XysAsync(mercs: Coordinate[]): Promise<(Coordinate)[]>;
        xys2MercsAsync(xys: Coordinate[]): Promise<Coordinate[]>;
    };
} & TBase;
export declare const META_KEYS: string[];
export declare function setCustomInitialize(self: any, options: any): void;
export declare function setupTileLoadFunction(target: any): void;
export {};
